#!/bin/sh
set -x
cmake . -B $BUILD_APP_DIR -G Ninja -DCMAKE_BUILD_TYPE=MinimumSize -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_POLICY_VERSION_MINIMUM=3.5
cmake ./tests -B $BUILD_TESTS_DIR -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1

